/***************************************************************/
/*                                                             */
/*      PROJECT NAME :  sensot_test                            */
/*      FILE         :  sensot_test.c                          */
/*      DESCRIPTION  :  Main Program                           */
/*      CPU SERIES   :  RX600                                  */
/*      CPU TYPE     :  RX621                                  */
/*                                                             */
/*      This file is generated by e2 studio.                   */
/*                                                             */
/***************************************************************/                                
                                                                           
                                                                           
/************************************************************************/
/*    File Version: V1.00                                               */
/*    Date Generated: 08/07/2013                                        */
/************************************************************************/

#include "iodefine.h"
#include "rxserial.h"
#include "i2c.h"

#ifdef CPPAPP
//Initialize global constructors
extern "C" void __main()
{
  static int initialized;
  if (! initialized)
    {
      typedef void (*pfunc) ();
      extern pfunc __ctors[];
      extern pfunc __ctors_end[];
      pfunc *p;

      initialized = 1;
      for (p = __ctors_end; p > __ctors; )
    (*--p) ();

    }
}
#endif 

int main(void)
{
    // TODO: add application code here

	volatile long i;
	char a0;
	int a;
	char str[10];
	unsigned char gyrostart[]={GCTRL_REG1, 0x8f};
	unsigned char readstatus[]={GSTATUS_REG};

	unsigned char readoutxl[]={GOUT_X_L};
	unsigned char readoutxh[]={GOUT_X_H};
	unsigned char readoutyl[]={GOUT_Y_L};
	unsigned char readoutyh[]={GOUT_Y_H};
	unsigned char readoutzl[]={GOUT_Z_L};
	unsigned char readoutzh[]={GOUT_Z_H};

	unsigned char data[100];

	unsigned char outxl, outxh ;
	unsigned char outyl, outyh ;
	unsigned char outzl, outzh ;
	unsigned short outx, outy, outz;
	char dummy[10];
	int val;

	a=0;

	PORTD.DR.BYTE = 1;

	//sendString("0123456789\r");
	//sendString("##########\r");
	//sendString("Hello Kouhei !!\r");
	//while(SCI_stop==0);
	//GYRO起動
	iic_write_data(GYRO, gyrostart, 2);

	for(i=0; i<100000;i++);
	iic_write_data(GYRO, readoutxl, 1);
	for(i=0; i<100000;i++);
	iic_read_data(GYRO, data, 1);
	while(1)PORTD.DR.BYTE = 3;


	outxl=data[0];
	iic_write_data(GYRO, readoutxh, 1);
	iic_read_data(GYRO, data, 1);
	outxh=data[0];

	//outxh=1;
	//outxl=1;
	val=outxh*256+outxl;
	//itoa(val, dummy);
	//sendString(dummy);
	//sendString("\r");

	#if 0
	for(i=0; i<100; i++){
		//GYRO Read Status
		do{
			iic_write_data(GYRO, readstatus, 1);
			iic_read_data(GYRO, data, 1);
		}while(data[0]==0);

		//Read OUT_X_L
		iic_write_data(GYRO, readoutxl, 1);
		iic_read_data(GYRO, data, 1);
		outxl=data[0];
		//Read OUT_X_H
		iic_write_data(GYRO, readoutxh, 1);
		iic_read_data(GYRO, data, 1);
		outxh=data[0];
		//Read OUT_Y_L
		iic_write_data(GYRO, readoutyl, 1);
		iic_read_data(GYRO, data, 1);
		outyl=data[0];
		//Read OUT_Y_H
		iic_write_data(GYRO, readoutyh, 1);
		iic_read_data(GYRO, data, 1);
		outyh=data[0];
		//Read OUT_Z_L
		iic_write_data(GYRO, readoutzl, 1);
		iic_read_data(GYRO, data, 1);
		outzl=data[0];
		//Read OUT_Z_H
		iic_write_data(GYRO, readoutzh, 1);
		iic_read_data(GYRO, data, 1);
		outzh=data[0];

		outx=outxh*256+outxl;
		outy=outyh*256+outyl;
		outz=outzh*256+outzl;

		itoa(outx, dummy);
		sendString(dummy);
		itoa(outy, dummy);
		sendString(dummy);
		itoa(outz, dummy);
		sendString(dummy);

	}

#endif



	//itoa(a,str);
	//sendString(str);

	//sendString("OK\r");
	//a++;


    while (1) {

    	//PORTD.DR.BYTE = 3;
    }
    return 0;
}
